// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OurBigDay.Api.Data;

#nullable disable

namespace OurBigDay.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260201093203_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OurBigDay.Api.Entities.WeddingDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("DayNumber")
                        .HasColumnType("int");

                    b.Property<string>("ThemeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WeddingDays");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateOnly(2025, 3, 14),
                            DayNumber = 1,
                            ThemeName = "Sangeet"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateOnly(2025, 3, 15),
                            DayNumber = 2,
                            ThemeName = "Night Before"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateOnly(2025, 3, 16),
                            DayNumber = 3,
                            ThemeName = "Christian Wedding"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
