// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OurBigDay.Api.Data;

#nullable disable

namespace OurBigDay.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260530140000_AddPaymentsAndImages")]
    partial class AddPaymentsAndImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id").HasColumnType("text");
                    b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().HasColumnType("text");
                    b.Property<string>("Name").HasMaxLength(256).HasColumnType("character varying(256)");
                    b.Property<string>("NormalizedName").HasMaxLength(256).HasColumnType("character varying(256)");
                    b.HasKey("Id");
                    b.HasIndex("NormalizedName").IsUnique().HasDatabaseName("RoleNameIndex");
                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<string>("ClaimType").HasColumnType("text");
                    b.Property<string>("ClaimValue").HasColumnType("text");
                    b.Property<string>("RoleId").IsRequired().HasColumnType("text");
                    b.HasKey("Id");
                    b.HasIndex("RoleId");
                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<string>("ClaimType").HasColumnType("text");
                    b.Property<string>("ClaimValue").HasColumnType("text");
                    b.Property<string>("UserId").IsRequired().HasColumnType("text");
                    b.HasKey("Id");
                    b.HasIndex("UserId");
                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider").HasColumnType("text");
                    b.Property<string>("ProviderKey").HasColumnType("text");
                    b.Property<string>("ProviderDisplayName").HasColumnType("text");
                    b.Property<string>("UserId").IsRequired().HasColumnType("text");
                    b.HasKey("LoginProvider", "ProviderKey");
                    b.HasIndex("UserId");
                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId").HasColumnType("text");
                    b.Property<string>("RoleId").HasColumnType("text");
                    b.HasKey("UserId", "RoleId");
                    b.HasIndex("RoleId");
                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId").HasColumnType("text");
                    b.Property<string>("LoginProvider").HasColumnType("text");
                    b.Property<string>("Name").HasColumnType("text");
                    b.Property<string>("Value").HasColumnType("text");
                    b.HasKey("UserId", "LoginProvider", "Name");
                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OurBigDay.Api.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id").HasColumnType("text");
                    b.Property<int>("AccessFailedCount").HasColumnType("integer");
                    b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().HasColumnType("text");
                    b.Property<string>("DisplayName").IsRequired().HasColumnType("text");
                    b.Property<string>("Email").HasMaxLength(256).HasColumnType("character varying(256)");
                    b.Property<bool>("EmailConfirmed").HasColumnType("boolean");
                    b.Property<bool>("LockoutEnabled").HasColumnType("boolean");
                    b.Property<DateTimeOffset?>("LockoutEnd").HasColumnType("timestamp with time zone");
                    b.Property<string>("NormalizedEmail").HasMaxLength(256).HasColumnType("character varying(256)");
                    b.Property<string>("NormalizedUserName").HasMaxLength(256).HasColumnType("character varying(256)");
                    b.Property<string>("PasswordHash").HasColumnType("text");
                    b.Property<string>("PhoneNumber").HasColumnType("text");
                    b.Property<bool>("PhoneNumberConfirmed").HasColumnType("boolean");
                    b.Property<string>("SecurityStamp").HasColumnType("text");
                    b.Property<bool>("TwoFactorEnabled").HasColumnType("boolean");
                    b.Property<string>("UserName").HasMaxLength(256).HasColumnType("character varying(256)");
                    b.HasKey("Id");
                    b.HasIndex("NormalizedEmail").HasDatabaseName("EmailIndex");
                    b.HasIndex("NormalizedUserName").IsUnique().HasDatabaseName("UserNameIndex");
                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("OurBigDay.Api.Entities.Category", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<string>("Name").IsRequired().HasColumnType("text");
                    b.HasKey("Id");
                    b.ToTable("Categories");
                    b.HasData(
                        new { Id = 1, Name = "Venue" }, new { Id = 2, Name = "Food" }, new { Id = 3, Name = "Photographer" },
                        new { Id = 4, Name = "Garlands" }, new { Id = 5, Name = "Clothes" }, new { Id = 6, Name = "Pundith" },
                        new { Id = 7, Name = "Cool drinks/water" }, new { Id = 8, Name = "Bridal wear (Hindu)" }, new { Id = 9, Name = "Drinks" },
                        new { Id = 10, Name = "Decor" }, new { Id = 11, Name = "Music" }, new { Id = 12, Name = "Mendi outfit" },
                        new { Id = 13, Name = "Invites" }, new { Id = 14, Name = "Pastor" }, new { Id = 15, Name = "Photography" },
                        new { Id = 16, Name = "Bridal wear (Christian)" }, new { Id = 17, Name = "MC" }, new { Id = 18, Name = "Cake" },
                        new { Id = 19, Name = "Party favours" }, new { Id = 20, Name = "Bridesmaids boxes" }, new { Id = 21, Name = "Groomsmen boxes" },
                        new { Id = 22, Name = "Flowers" }, new { Id = 23, Name = "Confetti" }, new { Id = 24, Name = "Violinist" },
                        new { Id = 25, Name = "Alcohol" }, new { Id = 26, Name = "360 Booth" }, new { Id = 27, Name = "Band" },
                        new { Id = 28, Name = "DJ" }, new { Id = 29, Name = "Speeches" }, new { Id = 30, Name = "Vows" },
                        new { Id = 31, Name = "Handfasting" }, new { Id = 32, Name = "Rehearsals" }, new { Id = 33, Name = "Mendhi Artists" });
                });

            modelBuilder.Entity("OurBigDay.Api.Entities.DayCategory", b =>
                {
                    b.Property<int>("DayId").HasColumnType("integer");
                    b.Property<int>("CategoryId").HasColumnType("integer");
                    b.Property<int>("DisplayOrder").HasColumnType("integer");
                    b.HasKey("DayId", "CategoryId");
                    b.HasIndex("CategoryId");
                    b.ToTable("DayCategories");
                    b.HasData(
                        new { DayId = 4, CategoryId = 1, DisplayOrder = 1 }, new { DayId = 4, CategoryId = 2, DisplayOrder = 2 },
                        new { DayId = 4, CategoryId = 33, DisplayOrder = 3 }, new { DayId = 4, CategoryId = 12, DisplayOrder = 4 },
                        new { DayId = 5, CategoryId = 1, DisplayOrder = 1 }, new { DayId = 5, CategoryId = 2, DisplayOrder = 2 },
                        new { DayId = 5, CategoryId = 5, DisplayOrder = 3 }, new { DayId = 5, CategoryId = 10, DisplayOrder = 4 },
                        new { DayId = 1, CategoryId = 1, DisplayOrder = 1 }, new { DayId = 1, CategoryId = 2, DisplayOrder = 2 },
                        new { DayId = 1, CategoryId = 3, DisplayOrder = 3 }, new { DayId = 1, CategoryId = 4, DisplayOrder = 4 },
                        new { DayId = 1, CategoryId = 5, DisplayOrder = 5 }, new { DayId = 1, CategoryId = 6, DisplayOrder = 6 },
                        new { DayId = 1, CategoryId = 7, DisplayOrder = 7 }, new { DayId = 1, CategoryId = 8, DisplayOrder = 8 },
                        new { DayId = 1, CategoryId = 9, DisplayOrder = 9 }, new { DayId = 1, CategoryId = 10, DisplayOrder = 10 },
                        new { DayId = 1, CategoryId = 11, DisplayOrder = 11 }, new { DayId = 1, CategoryId = 12, DisplayOrder = 12 },
                        new { DayId = 3, CategoryId = 13, DisplayOrder = 1 }, new { DayId = 3, CategoryId = 1, DisplayOrder = 2 },
                        new { DayId = 3, CategoryId = 14, DisplayOrder = 3 }, new { DayId = 3, CategoryId = 10, DisplayOrder = 4 },
                        new { DayId = 3, CategoryId = 15, DisplayOrder = 5 }, new { DayId = 3, CategoryId = 16, DisplayOrder = 6 },
                        new { DayId = 3, CategoryId = 17, DisplayOrder = 7 }, new { DayId = 3, CategoryId = 18, DisplayOrder = 8 },
                        new { DayId = 3, CategoryId = 19, DisplayOrder = 9 }, new { DayId = 3, CategoryId = 20, DisplayOrder = 10 },
                        new { DayId = 3, CategoryId = 21, DisplayOrder = 11 }, new { DayId = 3, CategoryId = 2, DisplayOrder = 12 },
                        new { DayId = 3, CategoryId = 22, DisplayOrder = 13 }, new { DayId = 3, CategoryId = 23, DisplayOrder = 14 },
                        new { DayId = 3, CategoryId = 24, DisplayOrder = 15 }, new { DayId = 3, CategoryId = 25, DisplayOrder = 16 },
                        new { DayId = 3, CategoryId = 26, DisplayOrder = 17 }, new { DayId = 3, CategoryId = 27, DisplayOrder = 18 },
                        new { DayId = 3, CategoryId = 28, DisplayOrder = 19 }, new { DayId = 3, CategoryId = 29, DisplayOrder = 20 },
                        new { DayId = 3, CategoryId = 30, DisplayOrder = 21 }, new { DayId = 3, CategoryId = 4, DisplayOrder = 22 },
                        new { DayId = 3, CategoryId = 31, DisplayOrder = 23 }, new { DayId = 3, CategoryId = 32, DisplayOrder = 24 },
                        new { DayId = 3, CategoryId = 3, DisplayOrder = 25 }, new { DayId = 3, CategoryId = 33, DisplayOrder = 26 });
                });

            modelBuilder.Entity("OurBigDay.Api.Entities.WeddingDay", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<DateOnly>("Date").HasColumnType("date");
                    b.Property<int>("DayNumber").HasColumnType("integer");
                    b.Property<string>("ThemeName").IsRequired().HasColumnType("text");
                    b.HasKey("Id");
                    b.ToTable("WeddingDays");
                    b.HasData(
                        new { Id = 4, Date = new DateOnly(2026, 12, 16), DayNumber = 1, ThemeName = "Mendhi" },
                        new { Id = 5, Date = new DateOnly(2026, 12, 17), DayNumber = 2, ThemeName = "Haldi" },
                        new { Id = 1, Date = new DateOnly(2026, 12, 18), DayNumber = 3, ThemeName = "Hindu Wedding & Night Before/Sangeet" },
                        new { Id = 3, Date = new DateOnly(2026, 12, 19), DayNumber = 4, ThemeName = "Christian Wedding & Reception" });
                });

            modelBuilder.Entity("OurBigDay.Api.Entities.WeddingItem", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<string>("AttributesJson").HasColumnType("text");
                    b.Property<int>("CategoryId").HasColumnType("integer");
                    b.Property<int>("DayId").HasColumnType("integer");
                    b.Property<decimal?>("DepositPaid").HasPrecision(18, 2).HasColumnType("numeric(18,2)");
                    b.Property<decimal?>("EstimatedCost").HasPrecision(18, 2).HasColumnType("numeric(18,2)");
                    b.Property<string>("ImagesJson").HasColumnType("text");
                    b.Property<string>("Name").IsRequired().HasColumnType("text");
                    b.Property<string>("Notes").HasColumnType("text");
                    b.Property<decimal?>("OutstandingFees").HasPrecision(18, 2).HasColumnType("numeric(18,2)");
                    b.Property<decimal?>("PercentageComplete").HasPrecision(5, 2).HasColumnType("numeric(5,2)");
                    b.Property<string>("VendorName").HasColumnType("text");
                    b.HasKey("Id");
                    b.HasIndex("CategoryId");
                    b.HasIndex("DayId");
                    b.ToTable("WeddingItems");
                });

            modelBuilder.Entity("OurBigDay.Api.Entities.WeddingItemPayment", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<decimal>("Amount").HasPrecision(18, 2).HasColumnType("numeric(18,2)");
                    b.Property<string>("Note").HasColumnType("text");
                    b.Property<DateOnly>("PaidDate").HasColumnType("date");
                    b.Property<int>("WeddingItemId").HasColumnType("integer");
                    b.HasKey("Id");
                    b.HasIndex("WeddingItemId");
                    b.ToTable("WeddingItemPayments");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null).WithMany().HasForeignKey("RoleId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("OurBigDay.Api.Entities.ApplicationUser", null).WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("OurBigDay.Api.Entities.ApplicationUser", null).WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null).WithMany().HasForeignKey("RoleId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("OurBigDay.Api.Entities.ApplicationUser", null).WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("OurBigDay.Api.Entities.ApplicationUser", null).WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                });

            modelBuilder.Entity("OurBigDay.Api.Entities.DayCategory", b =>
                {
                    b.HasOne("OurBigDay.Api.Entities.Category", "Category").WithMany("DayCategories").HasForeignKey("CategoryId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("OurBigDay.Api.Entities.WeddingDay", "WeddingDay").WithMany("DayCategories").HasForeignKey("DayId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Category");
                    b.Navigation("WeddingDay");
                });

            modelBuilder.Entity("OurBigDay.Api.Entities.WeddingItem", b =>
                {
                    b.HasOne("OurBigDay.Api.Entities.Category", "Category").WithMany("WeddingItems").HasForeignKey("CategoryId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.HasOne("OurBigDay.Api.Entities.WeddingDay", "WeddingDay").WithMany("WeddingItems").HasForeignKey("DayId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Category");
                    b.Navigation("WeddingDay");
                });

            modelBuilder.Entity("OurBigDay.Api.Entities.WeddingItemPayment", b =>
                {
                    b.HasOne("OurBigDay.Api.Entities.WeddingItem", "WeddingItem").WithMany("Payments").HasForeignKey("WeddingItemId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("WeddingItem");
                });

            modelBuilder.Entity("OurBigDay.Api.Entities.Category", b =>
                {
                    b.Navigation("DayCategories");
                    b.Navigation("WeddingItems");
                });

            modelBuilder.Entity("OurBigDay.Api.Entities.WeddingDay", b =>
                {
                    b.Navigation("DayCategories");
                    b.Navigation("WeddingItems");
                });

            modelBuilder.Entity("OurBigDay.Api.Entities.WeddingItem", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
